### ISSUE TITLE
Doesn't handle .well-known/host-meta, causing false "maybe down" reports

### ISSUE THREAD

**Issue by dos1** [lucahammer/fedifinder#132]
Fedifinder doesn't handle the case of an instance running on a different domain than the one the accounts are on.

For example, my handle is `dos@librem.one`, which points to `https://social.librem.one/@dos` via https://librem.one/.well-known/host-meta. Fedifinder however considers `social.librem.one` URLs to be different than `librem.one` handles, and marks `librem.one` ones as "Maybe down, maybe not Fediverse."

**Comment by lucahammer** [comment]
I would recommend to redirect webfinger: https://webfinger.net/lookup/?resource=dos%40librem.one

**Comment by dos1** [comment]
I don't control that instance, I can only suggest such change to its admins. However, as far as I understand, it's configured correctly with `host-meta` pointing to correct WebFinger URL already (`https://social.librem.one/.well-known/webfinger?resource={uri}`).

**Comment by dlitz** [comment]
I've had the same issue.  host-meta is what Mastodon uses and [instructs users to use](https://github.com/mastodon/documentation/blob/491e44c3465071c9671e379e6470ec6a80230399/Running-Mastodon/Serving_a_different_domain.md).

I actually thought until recently that Fedifinder did the right thing already, but here's my bug report to Debirdify (which has since been fixed over there): https://github.com/pruvisto/debirdify/issues/21

**Comment by lucahammer** [comment]
Fedifinder used host-meta in the past, but people were complaining, so I switched to webfinger as the primary method. I assumed it uses host-meta as well to find the webfinger address, but that doesn't seem to be the case.

It uses https://github.com/silverbucket/webfinger.js and I will have to check why and when it fails.
