### ISSUE TITLE
Fedifinder 1 and 2 disagree with number of followings

### ISSUE THREAD

**Issue by cjdb** [lucahammer/fedifinder#144]
Fedifinder: 
![image](https://user-images.githubusercontent.com/8622748/202938294-142ee33f-af6c-4f68-81c7-d30f807662b2.png)

Fedifinder 2: 
![image](https://user-images.githubusercontent.com/8622748/202938256-6302a881-837f-49de-a4ed-2b3c1df9489e.png)

Neither seem to be accurate though, as it should be at least 84.

**Comment by lucahammer** [comment]
You follow 413 accounts on Twitter, so the amount of scanned accounts is correct. (+1 because your own profile is scanned as well). 

I am looking into the amount of identified accounts. Those discrepancies are probably related to the regex for handle detection as well as cached domains and responsiveness of uncached domains.

Why do you think 84 would be the correct amount?

**Comment by lucahammer** [comment]
I found the bug. There was a mixup in variable names and the new version didn't look at pinned Tweets because of that.
